version: '3.8'

services:
  frontend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_VERSION=18.20.3
      - YARN_VERSION=1.22.19
      - NODE_ENV=production
    command: npm run start 
