version: '3.8'

services:
  frontend:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: npm run dev --prefix calander-app
